spring:
  application:
    name: companies-crud
  profiles:
    default: default
    # default: prod / qa
  config:
    import: "optional:configserver:http://localhost:7777"
  datasource:
    username: ${db.username}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    url: ${db.url}
    password:  ${db.password}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    context-path: /companies-crud
  port: 8081

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"

client:
  service-url:
    defaultZone: http://localhost:8761/eureka/