spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: companies-crud
              uri: http://localhost:8081
              predicates:
                - Path=/companies-crud/company/**
            - id: report-ms
              uri: http://localhost:7070
              predicates:
                - Path=/report-ms/report/**

profiles:
  default: default

server:
  port: 4040

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/